### ISSUE TITLE
Feature request: add a menu command that opens the video menu with the audio menu as a submenu 

### ISSUE THREAD

**Issue by microraptor** [christoph-heinrich/mpv-quality-menu#23]
I think it would be convenient to have a command like `script-binding quality_menu/menu_toggle` which opens the normal video_format menu, but has something like this item at the top: "_**Audio Streams...**_        open audio format menu". Clicking on this item opens the audio-format menu. 

This would be somewhat similar to how uosc's subtitle select menu also has a special "load" item on top:
![scr_2023-01-14_20-02-39](https://user-images.githubusercontent.com/15663536/212493641-f21356d6-17f2-416b-b6d8-9516a629d3d8.png)

This functionality be a fitting for rerouting the original quality select command of uosc and still have the ability to select audio.

Different question: Is there a reason why the codec, size and bitrate are not displayed on the right side of the menu in the smaller grayer font, like the native uosc menus? The codecs have often completely different string lengths, but if the uosc menu items were formatted like this, it would look much more cleanly and aligned I think:  
`Resolution FPS              codec, size, bitrate`

**Comment by christoph-heinrich** [comment]
> Is there a reason why the codec, size and bitrate are not displayed on the right side of the menu in the smaller grayer font, like the native uosc menus?

I actually tried it like that back in the day when I made the integration, but things didn't at all line up vertically, making comparing formats much harder. That might have been solved by something like you suggested, but there were also severe clipping issues. The menu has improved a lot since then, so it that might work much better now. Narrow windows could still be a problem with clipping though because the item title and hint both get clipped proportionally.

I have since then introduced fully configurable columns, so it should also be configurable what goes where in the uosc menu. How would you suggest that should work?
I could introduce a different separator for where it should get split and then reverse the order of columns on the right hand side + invert alignment when shown in uosc. Do you think that would be confusing?

Also don't expect that to get done anytime soon :wink:.

> "Audio Streams... open audio format menu"

I have already wondered how to make the integration with rerouting more seamless. I'll have a look after the rerouting thing gets merged, but no ETA on that.

**Comment by microraptor** [comment]
``> I have since then introduced fully configurable columns, so it should also be configurable what goes where in the uosc menu. How would you suggest that should work?
> I could introduce a different separator for where it should get split and then reverse the order of columns on the right hand side + invert alignment when shown in uosc. Do you think that would be confusing?

Sorry, I somehow completely overlooked the columns config. But that does sound too confusing 😅️. I think the issue here is that we are trying to have the the same option for uosc and text users. My suggestion is to maybe just split it up like this:

```
# Columns for a graphical (uosc) menu; primary part is left-aligned; secondary is right-aligned
graphical_columns_video_primary=resolution,frame_rate,dynamic_range
graphical_columns_video_secondary=language,codec_video,size,bitrate_total
graphical_columns_audio_primary=...
graphical_columns_audio_secondary=...

# Columns for a text-based menu; prefix individual columns with "-" to align left
text_columns_video=-resolution,frame_rate,dynamic_range,language,bitrate_total,size,-codec_video,-codec_audio
columns_audio=audio_sample_rate,bitrate_total,size,language,-codec_audio
```

**Comment by christoph-heinrich** [comment]
I have now implemented the title-hint-split in the branch [uosc_hint](https://github.com/christoph-heinrich/mpv-quality-menu/tree/uosc_hint) in case you want to try it out.

**Comment by christoph-heinrich** [comment]
The menu switching thing is now implemented in [menu_switch_entry](https://github.com/christoph-heinrich/mpv-quality-menu/tree/menu_switch_entry)

Merging both branches together creates a conflict, but it's easy to resolve. Here is a screenshot of both:
![image](https://user-images.githubusercontent.com/8932183/215884425-8ac7254f-ab26-45fc-9378-da16ea205067.png)

**Comment by christoph-heinrich** [comment]
Both features are now in master with 6e5f43ec87f96c92588ebe67bcc2d3341f686b27 and 49639158538c9ae248416d8010e0b8eda5a01246
