### ISSUE TITLE
Unable to switch quality

### ISSUE THREAD

**Issue by stl3** [christoph-heinrich/mpv-quality-menu#34]
When I try to switch to another quality, it just reloads the video but the quality is still the one I have by default. My mpv.conf profile settings:
```
[youtubeR]
profile-desc="ytbr"
script-opts=ytdl_hook-ytdl_path=F:\Scoop\apps\yt-dlp\current\yt-dlp
ytdl-format="(bestvideo[width<=1920][fps<=60][vcodec^=vp9]+bestaudio[acodec^=opus])[protocol=http]/299+140/137+251/best/bestvideo+bestaudio"
```
![mpv-shot0022](https://github.com/christoph-heinrich/mpv-quality-menu/assets/32008952/434ea222-1193-41be-9d9e-09b0f63af255)

![mpv-shot0023](https://github.com/christoph-heinrich/mpv-quality-menu/assets/32008952/db5a7359-f319-4b88-aa48-bc91a7bd9df2)

Seems stuck to 299+140. Is something wrong with the way I've done my mpv.conf settings that is causing a conflict somewhere that whenever quality-menu.lua tries to reload the vid with the new quality settings it gets ignored and keeps using the one from my profile or is it something else that I've missed? Let me know if other details are needed. 
`mpv v0.37.0-119-g0d47e484 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Dec 24 2023 00:14:21`

A few months back I updated to 4.1.1 from a version that did not even have a version set in the file (could be somewhere from 2022 or before). I only just noticed that it wasn't working now :o, appreciate any help.

Update: I simplified it to use `ytdl-format="bestvideo[height<=1080][fps<=60]+bestaudio/best"` and all is well now

**Comment by christoph-heinrich** [comment]
I wasn't able to reproduce it with your original example, but if it works now then I guess that's fine :smile:

**Comment by fidodido48** [comment]
I also experienced this with some videos. No matter what audio stream i choose its stuck on the one it loaded initially and wont change to anything else. It also happened when i was specifying my own custom ytdl-format, so i guess it breaks the script somehow.

**Comment by christoph-heinrich** [comment]
If you can provide steps for reproducing your issue, I might be able to do something about it, but I've tried changing audio on a youtube video that has audio in two different languages, and switching audio language worked without a problem.

I also use `ytdl-format` in my mpv.conf, so that's definitely not the problem either.

In the linked issue the problem was applying `ytdl-format` in a conditional profile, and there is nothing I can do about that. There is no way to tell mpv to not let anything else overwrite that property.
