### ISSUE TITLE
Menu not centered

### ISSUE THREAD

**Issue by Akhilesh-T** [christoph-heinrich/mpv-quality-menu#4]
The menu is going out of the window

![Screenshot_29072022-160200](https://user-images.githubusercontent.com/80357467/181741098-4ecbe83e-d68f-412f-80c9-9167775f2c21.png)

**Comment by christoph-heinrich** [comment]
Hard to say what could be causing this with such little information.

I can only achieve this with negative numbers for `text_padding_y`, but whatever is causing it for you, you should be able to move the text around with `text_padding_x` and `text_padding_y`.

Otherwise maybe this patch can help. It really shouldn't make a difference, but who knows...

``` diff
diff --git a/quality-menu.lua b/quality-menu.lua
index 4e7120d..8d1d561 100644
--- a/quality-menu.lua
+++ b/quality-menu.lua
@@ -520,6 +520,7 @@ local function show_menu(isvideo)
         local ass = assdraw.ass_new()
 
         ass:pos(opts.text_padding_x, opts.text_padding_y)
+        ass:an(7)
         ass:append(opts.style_ass_tags)
 
         if options[1] then
```

**Comment by Akhilesh-T** [comment]
Setting `text_padding_y = 260` fixed it. Thanks.
